### PR TITLE
Add line-by-line comments for http_parser_execute

### PR DESCRIPTION
**Pull request by AoiKuiyuyou**

### CODE REVIEW

**Comment by indutny** [comment]
Hello!

Thank you for contributing this. What's the motivation for this change?

**Comment by AoiKuiyuyou** [comment]
Just for readability. Line-by-line comments make the intention behind each line explicit so that future readers can understand the intention easily and read the code fast.

**Comment by indutny** [comment]
I'm afraid that it makes code less readable, because less code fits on the screen. Most of the comments are just copying what code below says, so the provided value is not high enough. Sorry, but I'm going to reject this PR.

**Comment by AoiKuiyuyou** [comment]
No problem. Thanks for handling the PR.

**Pull request closed without merging**
